language: c
sudo: false
branches:
only:
  - master
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes psutil yaml pyyaml
    #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then conda create --name gds --file content/infrastructure/gds_requirements_linux-64.txt; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then conda create --name gds --file content/infrastructure/gds_requirements_osx-64.txt; fi
  - "conda-env create -f content/infrastructure/install_gds_stack.yml"
  - source activate gds
  - pip install contextily

script: 
  - python -c "import fiona"
  - python -c "import pysal;import geopandas;s=geopandas.read_file(pysal.examples.get_path('columbus.shp'));s.crs['init']='epsg:26918';s.to_crs(epsg=4326)"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then jupyter nbconvert --to markdown --execute --ExecutePreprocessor.timeout=480 content/infrastructure/check_gds_stack.ipynb; fi
 #- cd content/labs
 #- jupyter nbconvert --execute --ExecutePreprocessor.timeout=120 *.ipynb

notifications:
    email:
        recipients:
            - daniel.arribas.bel@gmail.com
        on_failure: always


